{{- if or .Values.headplane.oidc.enabled .Values.headscale.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.headplane.oidc.secret_name | default "oidc-secrets" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if .Values.headplane.oidc.enabled }}
  HEADPLANE_OIDC__CLIENT_SECRET: "{{ .Values.headplane.oidc.client_secret | required "headplane.oidc.client_secret is required when OIDC is enabled" }}"
  HEADPLANE_OIDC__CLIENT_ID: "{{ .Values.headplane.oidc.client_id }}"
  {{- end }}
  {{- if .Values.headscale.oidc.enabled }}
  HEADSCALE_OIDC__CLIENT_SECRET: "{{ .Values.headscale.oidc.client_secret | required "headscale.oidc.client_secret is required when OIDC is enabled" }}"
  HEADSCALE_OIDC__CLIENT_ID: "{{ .Values.headscale.oidc.client_id }}"
  {{- end }}
{{- end }}
