apiVersion: v1
kind: Secret
metadata:
  name: headplane-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 3000
      cookie_secure: true
      cookie_secret: "{{ .Values.headplane.config.server.cookie_secret }}"
    headscale:
      url: "{{ .Values.headplane.config.headscale.url }}"
      config_path: "/etc/headscale/config.yaml"
      config_strict: "true"
    integration:
      kubernetes:
        enabled: true
        validate_manifest: true
        pod_name: "headplane-0"
{{- if .Values.headplane.oidc.enabled }}
    oidc:
      issuer: "{{ .Values.headplane.oidc.issuer | trimSuffix "/" }}{{- if not (hasSuffix "/.well-known/openid-configuration" .Values.headplane.oidc.issuer) }}/.well-known/openid-configuration{{- end }}"
      disable_api_key_login: {{ .Values.headplane.oidc.disable_api_key_login }}
      headscale_api_key: "placeholder"
      token_endpoint_auth_method: {{ .Values.headplane.oidc.token_endpoint_auth_method | quote }}
      redirect_uri: {{ .Values.headplane.oidc.redirect_uri | quote }}
      client_id: {{ .Values.headplane.oidc.client_id | quote }}
{{- end }}
